name = "singbox"
main = "src/index.js"
compatibility_date = "2025-04-16"
compatibility_flags = ["nodejs_compat"]
[observability]
enabled = true
# 环境变量
# [vars]
# SUB = ""
# IMG = ""
# BEIANURL = ""
# MIHOMO = ""
# BEIAN = ""